"""Alert model for notifications and maintenance recommendations."""
import uuid
from enum import Enum
from typing import TYPE_CHECKING, Optional
from datetime import datetime
from sqlalchemy import String, Boolean, ForeignKey, Text, DateTime
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, TimestampMixin

if TYPE_CHECKING:
    from .asset import Asset


class AlertSeverity(str, Enum):
    """Severity levels for alerts."""
    INFO = "info"           # Informational - no action required
    WARNING = "warning"     # Attention needed - schedule inspection
    CRITICAL = "critical"   # Urgent - immediate action required
    EMERGENCY = "emergency" # Equipment failure imminent/occurring


class AlertStatus(str, Enum):
    """Status of an alert."""
    ACTIVE = "active"               # New alert, needs attention
    ACKNOWLEDGED = "acknowledged"   # Seen by user, under review
    IN_PROGRESS = "in_progress"     # Work order created, being addressed
    RESOLVED = "resolved"           # Issue fixed
    DISMISSED = "dismissed"         # False positive or not applicable
    AUTO_RESOLVED = "auto_resolved" # Condition returned to normal


class FailureMode(str, Enum):
    """Common failure modes in metal fabrication equipment."""
    # Mechanical
    BEARING_WEAR = "bearing_wear"
    BEARING_LUBRICATION = "bearing_lubrication"
    SHAFT_MISALIGNMENT = "shaft_misalignment"
    SHAFT_IMBALANCE = "shaft_imbalance"
    GEAR_WEAR = "gear_wear"
    BELT_WEAR = "belt_wear"
    COUPLING_FAILURE = "coupling_failure"

    # Hydraulic
    PUMP_DEGRADATION = "pump_degradation"
    SEAL_WEAR = "seal_wear"
    VALVE_FAILURE = "valve_failure"
    HYDRAULIC_LEAK = "hydraulic_leak"
    CONTAMINATED_FLUID = "contaminated_fluid"

    # Electrical
    MOTOR_OVERLOAD = "motor_overload"
    MOTOR_INSULATION = "motor_insulation"
    ELECTRICAL_FAULT = "electrical_fault"
    POWER_QUALITY = "power_quality"

    # Thermal
    OVERHEATING = "overheating"
    COOLING_FAILURE = "cooling_failure"

    # Other
    FILTER_CLOGGED = "filter_clogged"
    PRESSURE_ABNORMAL = "pressure_abnormal"
    VIBRATION_EXCESSIVE = "vibration_excessive"
    ANOMALY_DETECTED = "anomaly_detected"
    UNKNOWN = "unknown"


class Alert(Base, TimestampMixin):
    """
    Alert represents a notification about equipment health.

    Alerts are generated by ML models when anomalies are detected
    or when predicted failures are imminent. Each alert includes
    plain-language explanations and recommended actions.
    """
    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )
    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("assets.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Alert Classification
    severity: Mapped[AlertSeverity] = mapped_column(
        SQLEnum(AlertSeverity),
        nullable=False,
        index=True
    )
    status: Mapped[AlertStatus] = mapped_column(
        SQLEnum(AlertStatus),
        default=AlertStatus.ACTIVE,
        nullable=False,
        index=True
    )
    failure_mode: Mapped[FailureMode] = mapped_column(
        SQLEnum(FailureMode),
        default=FailureMode.ANOMALY_DETECTED,
        nullable=False
    )

    # Alert Content (user-facing)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)  # Plain language explanation
    recommendation: Mapped[str] = mapped_column(Text, nullable=False)  # What to do

    # ML Model Details (explainability)
    confidence_score: Mapped[float] = mapped_column(default=0.0)  # 0-1
    model_version: Mapped[str] = mapped_column(String(50), nullable=False)
    trigger_reason: Mapped[str] = mapped_column(Text)  # Technical explanation
    contributing_factors: Mapped[Optional[dict]] = mapped_column(JSONB)  # Feature importances
    anomaly_score: Mapped[Optional[float]] = mapped_column()

    # Related Data
    sensor_ids: Mapped[Optional[list]] = mapped_column(JSONB)  # Sensors that triggered
    reading_ids: Mapped[Optional[list]] = mapped_column(JSONB)  # Specific readings
    prediction_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))

    # Timing
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    acknowledged_by: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    resolved_by: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))

    # Time Window
    predicted_failure_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    action_deadline: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    # Work Order Link
    work_order_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))

    # Notification Tracking
    notification_sent_email: Mapped[bool] = mapped_column(Boolean, default=False)
    notification_sent_sms: Mapped[bool] = mapped_column(Boolean, default=False)
    notification_sent_push: Mapped[bool] = mapped_column(Boolean, default=False)

    # User Feedback (for model improvement)
    feedback_accurate: Mapped[Optional[bool]] = mapped_column(Boolean)
    feedback_notes: Mapped[Optional[str]] = mapped_column(Text)
    feedback_given_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    feedback_given_by: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))

    # Relationships
    asset: Mapped["Asset"] = relationship(
        "Asset",
        back_populates="alerts"
    )

    @property
    def is_actionable(self) -> bool:
        """Check if alert requires user action."""
        return self.status in [AlertStatus.ACTIVE, AlertStatus.ACKNOWLEDGED]

    @property
    def severity_color(self) -> str:
        """Return color for UI display."""
        color_map = {
            AlertSeverity.INFO: "blue",
            AlertSeverity.WARNING: "yellow",
            AlertSeverity.CRITICAL: "orange",
            AlertSeverity.EMERGENCY: "red"
        }
        return color_map.get(self.severity, "gray")

    def __repr__(self) -> str:
        return f"<Alert(id={self.id}, severity={self.severity}, status={self.status}, title='{self.title[:30]}...')>"
